export enum MainFoodCategory {
    GARLIC_BREAD = 'GARLIC_BREAD',
    F_F ='F_F',
    SALAD = 'SALAD',
    SPINGROLL = 'SPINGROLL',
    SHOUP_VG = 'SHOUP_VG',
    PIZZA = 'PIZZA',
    HORT_NOODLE = 'HORT_NOODLE',
    HORT_SPICATI = 'HORT_SPICATI',
    FIRD_NOODLE = 'FIRD_NOODLE',
    FRID_RICE = 'FRID_RICE',

    STEAP_FISH = 'STEAP_FISH',
    CRAB_GINGER = 'CRAB_GINGER',
    BROW_PAPER = 'BROW_PAPER',
    CLAM_GRILL = 'CLAM_GRILL',
    BBQ_SEA_FOOD = 'BBQ_SEA_FOOD'
}
