export enum MainDrinkCategory{
    WATER = 'WATER',
    COCACOLA = 'COCACOLA',
    SPRITE = 'SPRITE',
    ORAGE_JUICE = 'ORAGE_JUICE',
    COLAN_JUICE = 'COLAN_JUICE',

    MIX_FRUIT_SHACK = 'MIX_FRUIT_SHACK',
    BANANA_SHACK = 'MIX_FRUIT_SHACK',
    APPLE_SHACK = 'APPLE_SHACK',
    CARROT_SHACK = 'CARROT_SHACK',
    ORANGE_JUICE = 'ORANGE_JUICE',

    ANCHOR_BEER = 'ANCHOR_BEER',
    ANGKOR_BEER = 'ANGKOR_BEER',
    CAMBODAI_BEER = 'CAMOBODAI_BEER',
    ABC_BEER = 'ABC_BEER',
    TIGER_BEER = 'TIGER_BEER',
    HAKNUMAN_BEER = 'HAKNUMAN_BEER',
}